import { useState } from 'react'
import { store } from '../store'
import { formatMoney, formatHours } from '../utils'
import { jsPDF } from 'jspdf'
import { FileText, Download, ChevronDown, Check } from 'lucide-react'

export function Invoices() {
  const [clientId, setClientId] = useState('')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const [generated, setGenerated] = useState(false)

  const clients = store.getClients()
  const projects = store.getProjects()
  const entries = store.getEntries()
  const invoices = store.getInvoices()

  // Filter entries for preview
  const filteredEntries = entries.filter(e => {
    const project = projects.find(p => p.id === e.projectId)
    if (!project) return false
    if (clientId && project.clientId !== clientId) return false
    if (dateFrom && e.date < dateFrom) return false
    if (dateTo && e.date > dateTo) return false
    return true
  })

  // Group by project
  const byProject = {}
  filteredEntries.forEach(e => {
    if (!byProject[e.projectId]) byProject[e.projectId] = { entries: [], totalMs: 0 }
    byProject[e.projectId].entries.push(e)
    byProject[e.projectId].totalMs += e.duration
  })

  const totalAmount = Object.entries(byProject).reduce((sum, [pid, data]) => {
    const project = projects.find(p => p.id === pid)
    return sum + (data.totalMs / 3600000) * (project?.hourlyRate || 0)
  }, 0)

  const generatePDF = () => {
    const client = clients.find(c => c.id === clientId)
    const doc = new jsPDF()
    const invoiceNum = `INV-${Date.now().toString(36).toUpperCase()}`
    let y = 20

    // Header
    doc.setFontSize(24)
    doc.setTextColor(30, 41, 59)
    doc.text('INVOICE', 20, y)
    y += 10

    doc.setFontSize(10)
    doc.setTextColor(148, 163, 184)
    doc.text(invoiceNum, 20, y)
    doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 190, y, { align: 'right' })
    y += 15

    // Client
    if (client) {
      doc.setFontSize(10)
      doc.setTextColor(100, 116, 139)
      doc.text('BILL TO', 20, y)
      y += 6
      doc.setFontSize(12)
      doc.setTextColor(30, 41, 59)
      doc.text(client.name, 20, y)
      y += 5
      if (client.email) {
        doc.setFontSize(10)
        doc.setTextColor(100, 116, 139)
        doc.text(client.email, 20, y)
        y += 5
      }
    }

    if (dateFrom || dateTo) {
      y += 3
      doc.setFontSize(9)
      doc.setTextColor(148, 163, 184)
      doc.text(`Period: ${dateFrom || 'Start'} to ${dateTo || 'Present'}`, 20, y)
    }
    y += 12

    // Table header
    doc.setFillColor(248, 250, 252)
    doc.rect(20, y - 4, 170, 8, 'F')
    doc.setFontSize(9)
    doc.setTextColor(100, 116, 139)
    doc.text('PROJECT / DESCRIPTION', 22, y)
    doc.text('HOURS', 120, y, { align: 'right' })
    doc.text('RATE', 150, y, { align: 'right' })
    doc.text('AMOUNT', 188, y, { align: 'right' })
    y += 8

    // Line items
    doc.setTextColor(30, 41, 59)
    Object.entries(byProject).forEach(([pid, data]) => {
      const project = projects.find(p => p.id === pid)
      if (!project) return
      const hours = data.totalMs / 3600000
      const amount = hours * (project.hourlyRate || 0)

      doc.setFontSize(10)
      doc.text(project.name, 22, y)
      doc.text(hours.toFixed(2), 120, y, { align: 'right' })
      doc.text(formatMoney(project.hourlyRate || 0), 150, y, { align: 'right' })
      doc.text(formatMoney(amount), 188, y, { align: 'right' })
      y += 6

      // Individual entries
      doc.setFontSize(8)
      doc.setTextColor(148, 163, 184)
      data.entries.forEach(e => {
        const desc = e.description || 'Time entry'
        const h = (e.duration / 3600000).toFixed(2)
        doc.text(`  ${e.date}  ${desc}  (${h}h)`, 24, y)
        y += 4
      })
      doc.setTextColor(30, 41, 59)
      y += 4
    })

    // Total
    y += 4
    doc.setDrawColor(226, 232, 240)
    doc.line(120, y, 190, y)
    y += 8
    doc.setFontSize(12)
    doc.setTextColor(30, 41, 59)
    doc.text('TOTAL', 120, y)
    doc.setFontSize(14)
    doc.setTextColor(22, 163, 74)
    doc.text(formatMoney(totalAmount), 188, y, { align: 'right' })

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(148, 163, 184)
    doc.text('Generated by Freelance Timer', 105, 285, { align: 'center' })

    doc.save(`${invoiceNum}.pdf`)

    // Save invoice record
    store.saveInvoice({
      number: invoiceNum,
      clientId,
      clientName: client?.name || 'All Clients',
      dateFrom,
      dateTo,
      totalAmount,
      entryCount: filteredEntries.length,
    })
    setGenerated(true)
    setTimeout(() => setGenerated(false), 3000)
  }

  return (
    <div className="space-y-4">
      <h2 className="text-lg font-semibold text-[#1e293b]">Generate Invoice</h2>

      <div className="bg-white rounded-xl p-4 border border-[#e2e8f0] space-y-3">
        <div className="relative">
          <select value={clientId} onChange={e => setClientId(e.target.value)}
            className="w-full px-3 py-2.5 bg-white border border-[#e2e8f0] rounded-lg text-sm appearance-none pr-8">
            <option value="">All clients</option>
            {clients.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
          </select>
          <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 text-[#94a3b8] pointer-events-none" />
        </div>
        <div className="grid grid-cols-2 gap-2">
          <div>
            <label className="text-xs text-[#94a3b8] mb-1 block">From</label>
            <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)}
              className="w-full px-3 py-2.5 border border-[#e2e8f0] rounded-lg text-sm" />
          </div>
          <div>
            <label className="text-xs text-[#94a3b8] mb-1 block">To</label>
            <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)}
              className="w-full px-3 py-2.5 border border-[#e2e8f0] rounded-lg text-sm" />
          </div>
        </div>
      </div>

      {/* Preview */}
      {filteredEntries.length > 0 && (
        <div className="bg-white rounded-xl border border-[#e2e8f0] overflow-hidden">
          <div className="px-4 py-3 border-b border-[#e2e8f0] flex items-center justify-between">
            <span className="text-sm font-medium text-[#1e293b]">{filteredEntries.length} entries</span>
            <span className="text-sm font-semibold text-[#16a34a]">{formatMoney(totalAmount)}</span>
          </div>
          <div className="divide-y divide-[#f1f5f9] max-h-48 overflow-y-auto">
            {Object.entries(byProject).map(([pid, data]) => {
              const project = projects.find(p => p.id === pid)
              return (
                <div key={pid} className="px-4 py-2 flex justify-between text-sm">
                  <span className="text-[#1e293b]">{project?.name || 'Unknown'}</span>
                  <span className="text-[#64748b]">{formatHours(data.totalMs)}h · {formatMoney((data.totalMs / 3600000) * (project?.hourlyRate || 0))}</span>
                </div>
              )
            })}
          </div>

          <div className="p-3">
            <button onClick={generatePDF}
              className={`w-full py-3 rounded-xl font-semibold text-white flex items-center justify-center gap-2 transition-all active:scale-[0.98] ${
                generated ? 'bg-[#16a34a]' : 'bg-[#2563eb] hover:bg-[#1d4ed8]'
              }`}>
              {generated ? <><Check className="w-5 h-5" /> Invoice Downloaded!</> : <><Download className="w-5 h-5" /> Generate & Download PDF</>}
            </button>
          </div>
        </div>
      )}

      {filteredEntries.length === 0 && (
        <div className="text-center py-8 text-[#94a3b8]">
          <FileText className="w-10 h-10 mx-auto mb-3 opacity-40" />
          <p className="text-sm">No entries match your filters.</p>
          <p className="text-xs mt-1">Track some time, then come back to invoice.</p>
        </div>
      )}

      {/* Past invoices */}
      {invoices.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-[#1e293b] mb-2">Past Invoices</h3>
          <div className="bg-white rounded-xl border border-[#e2e8f0] divide-y divide-[#f1f5f9] overflow-hidden">
            {invoices.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).map(inv => (
              <div key={inv.id} className="px-4 py-3 flex items-center justify-between">
                <div>
                  <div className="font-medium text-sm text-[#1e293b]">{inv.number}</div>
                  <div className="text-xs text-[#94a3b8]">{inv.clientName} · {inv.entryCount} entries</div>
                </div>
                <div className="text-sm font-semibold text-[#16a34a]">{formatMoney(inv.totalAmount)}</div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
